### ISSUE TITLE
No radial menu and no text

### ISSUE THREAD

**Issue by libereee** [liberated-cortex/CCOSS#12]
I am using the Linux version, specifically "Linux build 19 November 2019".

Whenever you right-click in the game you should see a radial menu and a cursor. However, it doesn't appear. Furthermore there is no text in the tutorial mission.

**Comment by Smilex** [comment]
Thanks for the report!

Turns out that my machine with the older LIBC, builds a broken game. If you have time, could you try this new update I just released - https://github.com/liberated-cortex/CCOSS/releases/tag/linux_12_02_2020

**Comment by libereee** [comment]
I only did a quick test of the tutorial mission but it seems that both the text and the menu now appear. Thank you very much! :)
