### ISSUE TITLE
Cortex Command won't build on linux

### ISSUE THREAD

**Issue by ghost** [liberated-cortex/CCOSS#15]
I'm having an issue with building it. After running each command on the readme for building on linux I get stuck on `make PREPARED_DIR=../CCOSS_dependencies/prepared/ -j4` Using the master branch, it tells me that it couldn't find `allegro.h`, and on the linux branch it tells me there is no makefile. How do I fix this? Thank you for helping and porting this to linux.

**Comment by Smilex** [comment]
The "./prepare.sh" step must have failed.

Can you confirm that there's no "allegro.h" in CCOSS_dependencies/prepared/include? And confirm that the file is not in "CCOSS_dependencies/prepared/"

And check if there's a allegro.h in "CCOSS_dependencies/allegro5-4.4.3.1/install/include"

**Comment by ghost** [comment]
allegro.h is only on `CCOSS_dependencies/allegro5-4.4.3.1/install/include`, not on the other directories. also the linux branch is missing a makefile, which is what caused it to say there is no makefile (duh). i copied the makefile to the linux branch and told me allegro was missing aswell.

**Comment by Smilex** [comment]
I didn't use branches for this, so I don't know what the Linux branch is. It's probably from the original CCOSS, so you shouldn't use it

**Comment by Smilex** [comment]
Can you confirm that when you run ./prepare.sh, no errors happen?
It's easier to notice if you just run ./allegro.sh

**Comment by ghost** [comment]
Ok yes. it says GL/glu.h is missing. I installed the glu development package for my distribution (void) and it compiled! Maybe there should be a list of dependencies for building in the readme. Thank you!
